
name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
      
  Deploy-Dev:
    name: Deploy Teste
    runs-on: ubuntu-latest
    environment: dev
    needs: CI-Build
    steps:
    - name: Teste
      run: echo '!!! Deploy realizado com sucesso !!!'  
