
# name: .NET

# on:
  # push:
    # branches: [ "main" ]
  # pull_request:
    # branches: [ "main" ]

# jobs:
  # deploy-dev:
    # name: Deploy Teste
    # runs-on: ubuntu-latest
    # enviroment: dev
    # needs: build
    # steps:
    # - name: Teste
    # run: echo 'Deploy realizado com sucesso!!!'    